spring:
  application:
    name: auth-service # docker-compose servis ismi

  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: postgres # docker-composedan geliyor
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true # uygulama başlatıldığında otomatik çalışması için
    locations: classpath:db/migration
    baseline-on-migrate: true

  redis:
    host: redis # docker-compose servis ismi
    port: 6379

jwt:
  secret: mySecretKey123456789
  accessExpiration: 1800000 # 30 dk
  refreshExpiration: 3600000 # 1 saat
