# version : '3.9'
# services:
#   auth-service:
#     build: ./auth-service
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/authdb
#       - SPRING_DATASOURCE_USERNAME=authuser
#       - SPRING_DATASOURCE_PASSWORD=authpass
#       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#       - JWT_SECRET=your_jwt_secret_key
#     depends_on:
#       - authdb

#   authdb:
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=authdb
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - "5432:5432"


version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: auth-redis
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: c2VjdXJlYmFzZTY0ZW5jb2RlZGtleQ==
      JWT_ACCESSEXPIRATION: 1800000
      JWT_REFRESHEXPIRATION: 3600000

volumes:
  postgres_data:
