version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: c2VjdXJlYmFzZTY0ZW5jb2RlZGtleQ==
      JWT_ACCESSEXPIRATION: 1800000
      JWT_REFRESHEXPIRATION: 3600000
      eureka.client.serviceUrl.defaultZone : http://eureka-server:8761/eureka

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
   

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8081:8080"
    depends_on:
      - auth-service
      - eureka-server
    environment:
      JWT_SECRET: c2VjdXJlYmFzZTY0ZW5jb2RlZGtleQ==
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

volumes:
  postgres_data:
