version : '3.9'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=authuser
      - SPRING_DATASOURCE_PASSWORD=authpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - authdb

  authdb:
    image: postgres:13
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"