server:
  port: 8080

spring:
  application:
    name: gateway

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka
      register-with-eureka: true
      fetch-registry: true
      registry-fetch-interval-seconds: 10

  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
           - name: Retry
             args:
              retries: 2
              statuses: 
                - BAD_GATEWAY
                - GATEWAY_TIMEOUT
           - name: CircuitBreaker
             args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
           - name: Retry
             args:
              retries: 2
              statuses: 
                - BAD_GATEWAY
                - GATEWAY_TIMEOUT
           - name: CircuitBreaker
             args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user     


           
  redis :
    host: ${SPRING_REDIS_HOST} # docker-composedan geliyor
    port: ${SPRING_REDIS_PORT:6379} # default 6379


resilience4j:
  retry:
    instances:
      authServiceRetry:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException

  circuitbreaker:
    instances:
      authServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      userServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: ${JWT_SECRET}